### ISSUE TITLE
Koohii can't tell that 㚣 exists

### ISSUE THREAD

**Issue by picsi** [fabd/kanji-koohii#108]
More info: https://en.wiktionary.org/wiki/%E3%9A%A3

Error page: https://kanji.koohii.com/study/kanji/%E3%9A%A3

Any idea why?

**Comment by fabd** [comment]
Thanks.

I will look at it soon. I'm not sure it is in the database.

I created a constant here 

https://github.com/fabd/kanji-koohii/blob/master/lib/CJK.php#L51

But it doesn't seem to be used elsewhere.

I suspect the character is not in the database, and I might have to shrug it off, as it's a non trivial fix. I would have to fill in the data again from KANJIDIC / UNIHAN files... a lot of time spent to support a few rare characters in the Study pages, which I'd rather invest elsewhere. (What's odd is that the 12000+ characters already cover all main use Simplified, Traditional Chinese, as well as Japanese.)

Note there may be an alternative character for this that looks the same in the main CJK unified range.

**Comment by fabd** [comment]
Confirm it is not included in the database. Database covers CJK UNIFIED  range 0x4e00 0x9faf ([source code](https://github.com/fabd/kanji-koohii/blob/master/lib/CJK.php#L38)).

I could add "CJK Unified Extension A" however that would add 6500+ characters to the kanji table when only very, very few of them will ever be referenced on the website. In addition to the tiome investment parsing the additional entries, it will make the table larger for practically no benefit (as far as I can tell).

So for the time being I have to leave it as a "wontfix" until it makes sense otherwise.

Thank you very much for reporting the issue though!

**Comment by picsi** [comment]
Thanks for taking the time to take a look, @fabd. I figured there must've been a way to automatically generate koohii pages for any Han character, I didn't know all this work was involved.

If there was, maybe the site could have been extended to cover the kana, as well as Korean characters too.
