### ISSUE TITLE
HTTPS secure connection

### ISSUE THREAD

**Issue by magnonellie** [fabd/kanji-koohii#11]
Signing in to any website without a secure connection isn't a good thing. Google are planning to [present users with a red warning sign](https://security.googleblog.com/2016/09/moving-towards-more-secure-web.html) on all sites that are not on a secure connection in the future.

There are two alternatives here as far as I see:

1. Buy a certificate and use that
2. Configure Let's Encrypt with the website

Buying a certificate is slightly easier but using LE is cheaper and can be really handy when you set it up to renew automatically.

**Comment by fabd** [comment]
Definitely aware of this (>_>) .. I will post a more detailed plan later. Briefly: sounds like I might have to mover over to a new shared hosting since HostGator makes me pay for installation of a "free" certificate. HostGator isn't bad at all, but I hear they've been bought so I don't know what quality I can expect from them over the next years. And I'm not too fond of paying a certificate because that's a permanent cost. Hard to remove SSL when users have gotten used to the secure flag in their browser. I may as well move to something that has auto-renew of Let's Encrypt.

I also need to publish **staging** to the live site, to simplify the moving process.

I need to find good shared hosting solutions that have Let's Encrypt auto renew.

**Comment by fabd** [comment]
Reminders for me later:

* also dbl check all the links from http: to https:
** domain setting in the config files
** hardcoded links in the news posts (potentially add a transform in the post formatting)

**Comment by fabd** [comment]
Talked to the web host live chat this morning. Multi domain SSL is 80 USD. I need to upgrade account for the dedicated IP running approx. 5 € per month, so altogether approx 150 € / year  to have **mutli domain SSL*. That's totally manageable, could probably raise it to once a year.

Question now is whether I should move or not. The hosting is pretty decent overall. So hmm.

**Comment by fabd** [comment]
Breaking down for later:

- [ ] decide if I buy the 80 USD multi domain (3 domains) on HostGator or move servers (I don't think Let's Encrypt is reliable enough anyway, but it's a nice-to-have).

The problem here is that HostGator server seems quite good... I routinely fill the 30 GB space with backups and they don't pester me about it, it seems to use SSDs, and I've had few problems over the years so hmm. The major roadblock for me here is how do I know FOR SURE that the new host SQL, CPU memory etc will be better? Most of the shared hosting solutions I see don't give any hard details on the hardware.

The other hesitation I have is because if I buy a cert. with HostGator; I'm not sure I can move it later. But then again it's "only" 80 USD for a year and if I want to move servers 6 months later it's not a huge deal...

## Checklist

- [ ] fix all HTTP references in the codebase
  - [ ] ... and in the forum template (sidebar)
  - [ ] ... and in the forum posts (SQL search / replace ...)
  - [ ] update **deploy** scripts and pray they don't need further changes for the SSH access
