### ISSUE TITLE
Keyboard short cuts

### ISSUE THREAD

**Issue by anonmaxmustermann** [fabd/kanji-koohii#112]
It would be good to have a keyboard short-cut to save the changes when a story is entered. Then it is not necessary to click the 'Save changes' button. It would be also good to go to the next and previous kanji with the arrow keys in the study section.

**Comment by fabd** [comment]
Related

Usability - Enhance keyboard navigation #47

**Keyboard shortcuts for saving story** : wont fix

Since the user is typing into an input field, it will potentially collide with all kind of shortcuts that exist on the user's OS / browser , including shortcuts to handle special characters and so on. I've personally never seen a website do this.

The standard way to do this across all websites is to TAB out of the input field until the save button is in focus, and then activate it. (as of writing press TAB 2x, then ENTER or SPACE to activate the button).

**Cursor keys to navigate Study pages**
I'm not too fond of that sounds more like a native app functionality; where the app can handle such quick transitions between pages. On the browser I'd have to add debounce / throttle handling of the keyboard so if user press key quickly ten times it will only load one page. Why not. But to be frank with you it's the kind of thing I can't prioritize since it doesn't have a significant usability impact in my opinion and there's always going to be other things I need to fix.

I prefer to be honest it's a "wont fix" rather than leave this open indefinitely.

There is also the question of the real cause for this request. I suspect the real issue here is:

Website: have the search bar follow you as you scroll #64

Thank you for the feedbac, I appreeciate it. Don't hesitate to add your voice to other open items it can help me prioritize some things, or maybe motivate some contributions.
