### ISSUE TITLE
Bug on 念 ( Shared Stories list )

### ISSUE THREAD

**Issue by picsi** [fabd/kanji-koohii#115]
See Kiyoona's story in https://kanji.koohii.com/study/kanji/1590 

We get one story and four blank boxes. If I report a blank box, Kiyoona's box with text is toggled. Pretty weird bug.

**Comment by fabd** [comment]
Sounds like a discrepancy between stories and vote tables. I made changes in mid 2016 to improve performance seeing as 94% of stories are not public. The columns for votes were moved to another table and a unique `sid` key joins the two. I know the code isn't perfect so likely those are entries appearing in votes table but no longer in stories.

Fortunately it's not a breaking bug.

**Comment by fabd** [comment]
Need to run a query on live database to clean orphan rows. Live is fixed soon.

**Comment by fabd** [comment]
Okay, fix is live. 242 orphan rows have been deleted.

**However** because it's a non-breaking bug and there are not many such rows I prefer to not reset the templates for performance reasons. I don't have a simple way of selectively cleaning the affected cached templates (stories lists). So it will show for a while still.

The cache of the Stories List on the affected pages will update as soon as someone publishes a new story, or unpublishes, or votes a story (all of which invalidate the cache).

Thanks for the bug report! 👍
