### ISSUE TITLE
Flag emoji break stories

### ISSUE THREAD

**Issue by picsi** [fabd/kanji-koohii#119]
I tried writing a story including 🇲🇽, but there was a bug that didn't show the whole story.

**Comment by fabd** [comment]
Can you provide  a webpage from which I can copy / paste the character to reproduce the issue?

I assume the bug is that the story was truncated?

I tried pasting an emoji 🇩🇪 and it saves as

    qsdqsd emoji test 🇩🇪 test

Which is fine by me. I don't plan on supporting emoji encoding in the stories.

However the characters should be properly escaped or just removed.

**Comment by fabd** [comment]
If you can provide a scenario to reproduce the bug and describe the bug I will reopen issue. Otherwise I can't work on this.

As an aside, I have no intention to support emojis in stories. This will be detrimental in the long run. Stories should use words, not icons.

**Comment by picsi** [comment]
I'll keep adding stories and if I run into this again, I'll be sure to post how to reproduce it.

**Comment by picsi** [comment]
Here it is: https://kanji.koohii.com/study/kanji/1963

Check out the story by islandisto. There's more text after 💪, but it doesn't show up.

**Comment by picsi** [comment]
I also tried adding the symbol 𠂉 on another story and had the same problem.

**Comment by fabd** [comment]
Regarding #1963 you say "after the (flex emoji)" but I don't see an emoji there. Using the copy button returns "A *thread* strong enough to pull *Mount* Fuji would need to be a #heavy rope# " in the textbox. So if this text was cut short then it would have been at the moment of saving.

I can look at this but can we describe the bug as in what doesn't work as expected, and what is expected.

What is the bug? That pasting an emoji causes the remaining text to be cut off?

**Comment by picsi** [comment]
>What is the bug? That pasting an emoji causes the remaining text to be cut off?

Precisely. I'm copying the emojis from Telegram, so that may be an issue? I didn't think allowing emojis in stories would require extra steps, so it's kinda unfortunate that they'll not be an accessory for remembering stories 😕

**Comment by fabd** [comment]
The problem is that emojis are

* very subjective
* not guaranteed to show for everyone
* will eventually be substituted for primitives by some users, which is not a good idea. The Study page works with stories as *text*. It was never the goal to make mnemonics out of small pictures.

I believe the Study  pages provide better value overall with consistency, and focusing on writing.

If you want you can bring up the discussion on the forum, see what others think.

I do appreciate the feedback.
