### ISSUE TITLE
Overly-aggressive "corrections" when saving stories

### ISSUE THREAD

**Issue by hornlo** [fabd/kanji-koohii#130]
I wanted to insert the following text into a story.  Unfortunately, when saved, the simplified single-drop radical gets "corrected" to the traditional double-drop form:

>  "{辵}" is no longer used, "{辶}" is traditional, "辶" is simplified; Heisig books use simplified version

I see older stories that have the simplified form in them, so this used to work.

Please either provide a way to literally quote a character, or restrict corrections to within braces.

**Comment by fabd** [comment]
There is no intended correction for the encodings. Only basic punctuation.

There could be unintended change of encoding.

Can you paste the original one for testing, and also to rule out font issue. (2nd and 3rd characters in your post have the same variant on my screen with two drops).

**Comment by hornlo** [comment]
Sorry for the false alarm; issue can be closed.  Looks like it's a horribly convoluted browser/text-input/text-display/font issue.  99% of my kanji-koohii study is done from my iPad.  When I just now accessed the site via my Linux laptop, then copy/pasted the (one drop) character, it saved correctly, and displays correctly on both my iPad and laptop.  I'm using chrome on both devices.  I've included a screen shot from my laptop.

To further add to the annoyance, when I view the GitHub issue from iPad, my quoted text in the original entry displays (two drop) for both characters.  When viewed from my laptop, both appear as (one drop).  I think this is a font issue, not an encoding issue.

However, saving on the iPad does appear to be an encoding issue.

---- experiments ----

On iPad, I would select/copy the correct character (one drop) from another story, then paste it into the story edit box, where it displayed correctly while editing.  After saving, it would display as (two drop) and would be (two drop) when I edited the story again.

If I edit/save/export my stories from iPad, the CSV file contains the _**same UTF-8 encoding**_ for both characters.  I couldn't figure out any way to actually _save_ a (one drop) in the story.

If I edit/save/export my stories from Linux, the _**UTF-8 encodings are distinct**_ in the CSV file, and display correctly in the browsers.

However, displaying the CSV line in my gnome_terminal session (via grep or vim) displays them both as (one drop), although with different glyphs (as above) which are indistinguishable unless you pay close attention; they appear correct in a non-termnial-based text editor -- so, this instance is a font issue, not an encoding issue.

Entered via cut/paste, who knows how you'll see these; in this edit box, I see them as distinct, but both one-drop glyphs:

  one drop: "辶"
  two drop: "辶"

Arrgh.  This isn't usually something I usually pay much attention to, and I don't recall it being an issue in the past.  Since I've re-started using the site and updating my stories, I've run across problems like this several times.  I don't know if it really worked OK in the past and current software/fonts are trying to be more "helpful" or if I just wasn't paying as much attention before.

![road-primitive-story-linux](https://user-images.githubusercontent.com/576073/34917438-26a2dc34-f90c-11e7-8e54-575779857350.png)

**Comment by hornlo** [comment]
Urm, but they both saved as the same character, which displays as two-drop on iPad and one-drop on Linux.

**Comment by hornlo** [comment]
One last comment ... maybe allow HTML character entries to be saved as-is in stories, like "&amp;#x8FB6;" -> "&#x8FB6;" / "&amp;#36790;" -> "&#36790;" so at least the right Unicode value will be there, regardless of how it gets displayed?

**Comment by wtn** [comment]
Unicode normalization converts compatibility characters like U+FA66 (one dot form) to the unified character U+8FB6 (which has two dots in proper Japanese and Korean fonts, but may be displayed differently in other regions). Github is presumably normalizing text entered here, which is why they all appear with two dots.

The one dot form can be selected by enabling an OpenType feature in CSS. The simplest way would be to force all Kanji Koohii glyphs to `jp90`, since that's basically the _RTK_ style. Here's a [syntax example](https://helpx.adobe.com/typekit/using/open-type-syntax.html#jp90).

Alternately, you can select a specific form by using a two-character Ideographic Variation Sequence (IVS). Here's an HTML example that works in fonts that support the Adobe Japan collection:
```
<p lang="ja">&#x8fb6;&#xe0101; <!-- one dot, Adobe Japan -->
<p lang="ja">&#x8fb6;&#xe0102; <!-- two dots, Adobe Japan -->
```

The Japanese government released its own collection with different IVS, but it isn't widely supported yet, so using it requires installing IPAmj明朝 font (latest version [here](https://mojikiban.ipa.go.jp/1300.html), bottom of page) or the Hanazono Mincho fonts. This collection lets you choose from three forms of this character! You can see all three forms [here](https://mojikiban.ipa.go.jp/1bf7a30fda/result?q=対応するUCS:8FB6).

IVS examples for the IPA MJ sequences:
```
<p style="font-family: IPAmjMincho;">&#x8fb6;&#xe0102; <!-- one dot, JP IPA -->
<p style="font-family: IPAmjMincho;">&#x8fb6;&#xe0103; <!-- two dots, JP IPA -->
<p style="font-family: IPAmjMincho;">&#x8fb6;&#xe0104; <!-- one dot & squiggle, JP IPA -->
```

Finally, you *should* be able to select the compatibility form U+FA66 using variation sequence <U+8FB6,U+FE00>, but it seems not to be supported by my default Japanese font:
```
<p lang="ja">&#x8fb6; <!-- default with two dots -->
<p lang="ja">&#x8fb6;&#xfe00; <!-- variant with one dot -->
```

**Comment by wtn** [comment]
I tried entering such a two-character sequence in the story editor, and it chopped off everything after the first character in the sequence, presumably because it considers the second character to be illegal.

**Comment by fabd** [comment]
That's super interesting wtn. I didn't know about those OpenType CSS features.

Koohii doesn't do anything with the kanji encodings in stories. They are just saved as "utf8" in MySQL (which doesn't support 4 byte characters as "utf8mb4" would but I don't think this is the issue).

No the main problem I have with these encoding problems is that there is no concensus. Whatever fix I do, it's either not going to be supported somewhere (eg. super interesting css features wtn mentioned), or the user simply doesn't have the fonts to see the proper characters. Or the OS does something different with the characters, as hornlo pointed out.
