### ISSUE TITLE
Add Autosaving Capabilities

### ISSUE THREAD

**Issue by akbrai** [fabd/kanji-koohii#134]
It would be great if Kanji Koohii periodically saves automatically when doing reviews. I've lost hours of reviews from Windows updating by itself.

**Comment by fabd** [comment]
Hello,

In theory you can only lose up to approx 10 reviews as the flashcard page
syncs with the server the answers while retrieving the next batch of cards.

**Comment by fabd** [comment]
I will close the issue assuming this is in a "intended" state at this time.

On desktop there should be an alert in the browser before closing tab, or changing to a different URL. This reminds user to "end" the review to sync with server.

If Windows shuts down this is probably bypassed. But as I said you should never lose more than the last 10 reviews, as the flashcard page syncs to server every 10 cards. This is an acceptable tradeoff I made to avoid having to hit the server with every answered cards, as well as for performance that way the user is not stalled whenever they flip a card (since cards are "cached" in small batches before they appear).
