### ISSUE TITLE
Review - Add 'hard' keyboard shortcut to number row

### ISSUE THREAD

**Issue by Inclushe** [fabd/kanji-koohii#158]
It's slighty disorienting when I'm switching from reviewing in Anki to reviewing in Koohii when using the number row. In Anki, you hit 1/no 2/hard 3/yes 4/easy, while in Koohii, it's 1/no 2/yes 3/easy.

https://github.com/fabd/kanji-koohii/blob/d1f53992ebd95400541a50b85748c7f1e4594187/web/revtk/kanji-flashcardreview.juicy.js#L65-L69

It would be pretty trivial to update (i could send a pull request) but I'm not sure if it would mess with our fellow users if it were changed.

**Comment by fabd** [comment]
I agree if that is a good solid default in Anki. if that's what most people would use in Anki then it makes sense to aligh the shortcuts.

If I update the keybinds and people don't notice the news, worst case they use smaller intervals rather than higher (eg. "hard" instead of "yes").

My hunch is not a lot of people use these keybinds because when I added "Hard" setting I don't remember anybody asking me to do something about the shortcuts. ... So I'm leaning towards just going with this change.

The numpad key equivalent would have to be added as well. I'll have a look.
