### ISSUE TITLE
Add a way to mark a card as failed, without having to flip it and look at the kanji

### ISSUE THREAD

**Issue by Betadel** [fabd/kanji-koohii#163]
Use case: sometimes I remember the primitives (or "idea" of the primitive) and the overall story of a kanji, but don't actually remember how to draw a particular primitive itself. In these cases I want to mark the card as failed, but I don't want to see the kanji in the back because that will "spoil" the primitive I couldn't remember, and if that primitive is used in other kanji later in the review session I'll "remember" it now, but it's technically cheating. 

I find myself covering the screen with my hand while I flip it and mark it No, or doing it really fast so I don't see the kanji much...

I think a feature that allows you to directly mark the card as failed without flipping it would be very useful for me and many other people.

**Comment by fabd** [comment]
This seems easy to change. Though I wonder why I put a conditional " if card is flipped" in the first place. Perhaps I was concerned that the user doesn't have enough feedback, especially if they press one of the answer key by mistake... going from a un-flipped card to the next un-flipped card you may not notice.

I'll definitely address this. I'm kinda stuck refactoring the build. Then it would be interesting with the new build if I can finally use components like a Notification widget, then I could add a good visual feedback so that you can answer cards at any time.
