### ISSUE TITLE
Spaced Repetition

### ISSUE THREAD

**Issue by cherrychupachups** [fabd/kanji-koohii#174]
When I want to do my reviews for the day, on Spaced Repetition page, it says that I have already done my reviews when I actually haven't done my reviews. Does anyone else get the same error?

**Comment by fabd** [comment]
Hi @cherrychupachups it might be because of the timezone. The site doesn't intelligently guess your midnight time, and by default the SRS determiens new due cards on "midnight".

In Account Settings https://kanji.koohii.com/account/edit try changing the timezone. You can shift it forward/backward to make the new due cards come at a different time (eg. some people review late at night they prefer the "midnight" to be later like 4 am).

Also just in case make sure to add cards... it might be you have zero flashcards on a new account.

Let me know if this solves the issue.
