### ISSUE TITLE
Inability to register for Russians

### ISSUE THREAD

**Issue by samkova13** [fabd/kanji-koohii#181]
I cannot to register because of the “.ru” in my e-mail address

**Comment by fabd** [comment]
I'm sorry about that @samkova13 .

And I apologize for the very late reply...I now have some time for the project.

Some checks are in place because unfortunately there are "robots" that keep creating dummy accounts; I don't think they even care about Koohii, they're likely bots trying to access WordPress sites and such.

Many of these bots accounts you can tell because of the random generated names and emails. Many of these emails have a .ru address.

**Solution**

Please register with another email you own, or even a temporary one like mailinator (I don't think those are blocked). THEN, once you're in simply go to your **Account Settings** and set your .ru email address. This won't cause an issue. The check is just on registration.

**Comment by nnemkin** [comment]
Yay racism!
