### ISSUE TITLE
Logged in user, homescreen: Narrow text column

### ISSUE THREAD

**Issue by tbrams** [fabd/kanji-koohii#19]
The text summary columns seems to be squashed with lots of extra white margin to the right of the buttons.

![screenshot_20170116-091922](https://cloud.githubusercontent.com/assets/3058746/21969122/16000728-dbce-11e6-910b-6e6c16a69dc5.png)

Not a biggie, but @fabd, you might want to consider renaming the "Progress chart" button to simply "Progress" and giving the text column more space?

**Comment by fabd** [comment]
**Considering these changes:** (short of rethinking the whole page, for now)

Stack vertically label, and buttons.

Change the order

... "Progress chart" is the first thing new users go to I think based on the feedback I get. ( I hear about it because new users get confused as they look at the progress page, click "Test" , and then they email me asking why the Progress isn't updated. For this reason I have removed the Test links, and "Lesson" should be an option in the Kanji Review page )

... So probably first "Study", then "Review", then Progress. In the future better yet, maybe the Progress page should be removed if I want the site to be more flexible and no so bound to RTK's grouping by "lessons". In that case the home page can have a general progress bar towards whatever INDEX the user has selected (currently only 5th / 6th editions ).

So I'll just tweak layout , and reorder these for a start.

**Comment by rinre** [comment]
Sorry if this is the wrong place, just have a very small question regarding the  "progress chart". 
It proudly announces that I have completet RTK 1 but not RTK 2 (although I finished it). It is not so important, just wondering if that is how it is supposed to work. (I use old version of RTK, but changing to the new version didn 't seem to change it). If you decide to remove the RTK connection altogether would also be fine with me, but as long as it is there, maybe it should work for RTK 2 in the same way as RTK 1.
All the best,
Ernir

**Comment by fabd** [comment]
@rinre I think Progress Chart counts cards with one review, have to check at home. Are you sure there are no gaps at all? If so, please create an issue for the Progress Chart and add a screenshot to see if all the bars are green. Also in the future don't be afrait to ask on Gitter if you're not sure about what Issue to create or whether a Issue is needed.

**Comment by rinre** [comment]
@fabd Thanks, it does seem to be completely finished, so I created an issue. And got a Gitter account+app for the next time I have a question ;-)

**Comment by fabd** [comment]
- I refreshed the styles a bit
- added a "push" style button to make some links stand out + feedback with the :active style
- changed the layout

I'll consider this fixed for now as I tested also on 320px and the text will show in one line due to change of layout.

That said, the need to improve the Home page remains : _Improve flow for new users_ #36 and _Improve the Home screen_ #7
