### ISSUE TITLE
"Export your kanji flashcards" should include user's kanji stories

### ISSUE THREAD

**Issue by Inclushe** [fabd/kanji-koohii#257]
Title says it all.

**Comment by fabd** [comment]
Hi @Inclushe 

You can export stories, but it's not very intuitive I suppose.

Since users may not use Koohii SRS at all - there is a separate export for stories at https://kanji.koohii.com/study/mystories

![Screenshot 2022-03-21 at 12 43 58](https://user-images.githubusercontent.com/169391/159254647-e7d6378c-1ad7-49a1-8e62-b4fad7e391ae.png)

Stories could also be added to the flashcards export to make it simpler for users to adjust the data for input in another program - so I 'll leave the issue open. For now I guess you'd have to sort the tables and the copy/paste the columns in some tabular data app.
