### ISSUE TITLE
Searching for "-times" and clicking the corresponding kanji (#630) in the results takes the user to "olden times" (#35)

### ISSUE THREAD

**Issue by peytontucker** [fabd/kanji-koohii#288]
![image](https://user-images.githubusercontent.com/77820777/213868906-e52664a8-4d64-4914-9873-9cb26baa3b68.png)
Clicking the 回 kanji in the results will take you to the page for 旧.

**Comment by fabd** [comment]
Hey thanks a lot! This issue is fixed and just deployed as of writing. 

I think I 'll write a short blog post to explain - but briefly, the proper fix was that the Study page should always redirect with a URL that contains the kanji - not the keyword - which is the most portable URL that always works regardless what RTK edition the user is using or any custom keywords.

Thanks for taking the time to let me know!
