### ISSUE TITLE
Misspelled keyword, frame 1296

### ISSUE THREAD

**Issue by peytontucker** [fabd/kanji-koohii#292]
https://kanji.koohii.com/study/kanji/1296

Should be facsimil**e**

**Comment by fabd** [comment]
I'm looking at  this. Turns out it's more work than I thought. I need to do these fixes in the "source of truth" which are the datafiles that were fed in to scripts which initially populated the database. The scripts are completely out of date, some don't even run anymore.

But this is pretty cool. I'm updating the scripts - and I will be able to add them to the repository here - which wasn't the case before.

All this to say if you see other seemingly minor things let me know. Be aware though - the way Koohii works is we're managing old/new edition indexes - however we're not handling old/new edition keywords. To make things more sane for the developer - but also to match most user expectations - the site always shows the more up to date keywords as per last (6th) RTK edition Volume 1 and 3 - that is even if the user has Old Edition selected in the app.
