### ISSUE TITLE
Wrong kanji font selection on Android Sony phone?

### ISSUE THREAD

**Issue by tbrams** [fabd/kanji-koohii#33]
This might be a mobile specific issue, but on my Android Sony Phone, it seems like some of the characters show up in a slightly different, but for me confusing, typeface. Here is a Screenshot of one of them
![screenshot_20170122-063357](https://cloud.githubusercontent.com/assets/3058746/22178759/ef9e2692-e072-11e6-81bb-d7fed9a6bfdf.png)

And here is a screenshot from my laptop:

<img width="314" alt="screenshot 2017-01-22 07 11 15" src="https://cloud.githubusercontent.com/assets/3058746/22178764/10ceb5b6-e073-11e6-9a33-6d9dc09dc5a6.png">

**Comment by faneca** [comment]
Yep, that's a problem with your device's installed fonts. The first one shows the *food* radical's old version, while the second image shows the (correct, I think) *new* version of that radical (the one used through all 常用漢字, but bear in mind that the old version is the right one to use with some non-jōyō kanji).

Maybe someone with experience on a similar device can help you configure it correctly.

**Comment by fabd** [comment]
Hmm, yes this issue comes from time to time from desktop users too (eg. [Dealing with Joyo variants](http://forum.koohii.com/thread-13551.html).

There is no obviou solutions from my end besides having a curated list of picture based kanji, which would also be impossible for me to maintain.

Throughout the site I try to indicate to the browser that we want the Japanese font, as a minimum. This is the container for the flashcard kanji:

```html
<span class="... cj-k" lang="ja" xml:lang="ja">可</span>
```

The font selection is something that's come up, I guess we could have a useful Issue for this specific topic as I never settled on a definitive "best" font selection. However I don't know if it would solve the problem here. If you can somehow force different fonts in your settings and see changes, it would be interesting to know what fonts work for you on your Android device.

This is the current font selection in the CSS: 

```css
/* class names output by cjk_lang_ja() helper */
.cj-k { font-family:"Hiragino Mincho Pro", "ヒラギノ明朝 Pro W3", "ＭＳ 明朝", "ＭＳ Ｐ明朝", serif; }
```

**Comment by tbrams** [comment]
I just tried this on another Android device - this time from Samsung. That device had the font, I have been used to seeing on the desktop as well. Seems strange that Sony might have it wrong in terms of installed fonts ... I would assume the Japanese knew what they were doing on that field ;-)

**Comment by fabd** [comment]
Closing as I don't think I can solve this problem on my end.

Note you can always comment on a closed item, and potentially they can be re-opened if we find something actionable.
