### ISSUE TITLE
Logo Scaling on Low DPI

### ISSUE THREAD

**Issue by magnonellie** [fabd/kanji-koohii#39]
When using a normal (1080p for example) display without any scaling in Chrome (or any other browser) or on the OS, the logo has to be scaled down, causing it to appear slightly blurry. This isn't a huge issue, but I still believe it should be fixed.

Here is an example of the difference between vector graphics and a PSD (rendered out as PNG) made with Inkscape:
![image](https://cloud.githubusercontent.com/assets/4590037/22187296/149ca022-e104-11e6-9ad5-b1513799ccd4.png)

And here are some links to the source files:
 - [raw (may have issues displaying fonts](https://drive.google.com/open?id=0B_PHDhAAxKKBMFdXUHg4QV9UdmM)
 - [pathified (no render issues)](https://drive.google.com/open?id=0B_PHDhAAxKKBTElTcW5vWjlDSEk)

**Comment by fabd** [comment]
Screenshot you posted recently on Gitter:

![blob](https://cloud.githubusercontent.com/assets/169391/22198355/82458696-e156-11e6-801b-8baec98b8cff.png)

**Comment by fabd** [comment]
For quick iterations I now created a [development room]() on Gitter.

The font is just close to what I wanted but not quite it. I wanted something friendly, and more balanced. So  eg. the h curve is too high and thinner compared to the rest. Which is why I'll want to be able to tweak the SVG.

**Comment by fabd** [comment]
Ok, the second file you linked to has the image in it. But I see that using a SVG image is pretty easy. So I'll get down to it eventually. The SVG file needs to be optimized and contain only the logo. The koohii letters I can make with shapes in Photoshop and convert , or maybe in Inkscape.

I'm labelling nice-to-have for now. prioritize later if people tend to notice it. I definitely want to learn Inkscape or how to easily convert PSD shapes to Inkscape because I'll need to make icons too.

Here is an optimize I came across on Github

https://github.com/svg/svgo-gui

**Comment by magnonellie** [comment]
Haha, no problem.

I think I am still gonna attempt at some mock-ups. I believe you should focus on the core website for now though.

About optimizing, I usually have a build task (gulp) that does that for me for all my images (gulp-imagemin, I believe). That includes SVG, PNG and JPEG.

**Comment by fabd** [comment]
Awesome, go ahead. We will iterate on Gitter. :+1:

**Comment by magnonellie** [comment]
Resolved by: #41
