### ISSUE TITLE
Landing page - Forum link missing

### ISSUE THREAD

**Issue by faneca** [fabd/kanji-koohii#52]
Maybe it's on purpose, but there is no link pointing to the forum for not-logged-in / anonymous users. Perhaps it would fit in the footer (or even as one of the showcased features).

I know there are more not linked "facilities" (like the wiki), but the forum seems like something to promote from the main page. Just my two cents.

**Comment by fabd** [comment]
It's intended so the link is not missing.

I want new visitors to be able to focus on the website to which they are introduced. For the same reason I removed a link that was in the first "showcase" (to the Help > "What is RTK") as I felt it was branching out too soon.

There are enough distractions on the web already. The goal of the landing page is to get someone who is curious, to sign up and just try it and see if that's what they're looking for. To that end the goal is to get the reader to scroll down the page and decide if they want to Register or not. Any links on the way to the bottom of the page is just distracting people from making that decision and it benefits nobody.

It's definitely not a showcased feature as the forum has taken a life of its own. There is no feedback subforum anymore. While there is some overlap in audience I'd say the forum is even more niche than the website since it's pretty intermediate / advanced topics. In my mind these are two audiences with some overlap.

Also, Kanji Koohii is pretty popular in non english countries like Brazil. I can see they have trouble on the signup form question sometimes, so I doubt it benefits them to send them straightaway to a relatively advanced learning forum. They can discover the forum later on their own. It's good enough that the forum is linked in the navigation for members.

**Comment by fabd** [comment]
> the forum seems like something to promote from the main page

I spent a ton of work on the forum upgrading it to MyBB and creating a completely new theme from scratch which is responsive and mobile friendly. The results? Nada. It's always been hovering around ~ 150 daily visitors.

It's healthy and it's carved its own little niche, but it's not growing in terms of active audience. The audience built itself originally around the "Reviewing the Kanji" user base, but nowadays it has incoming links from relatively advanced learning communities and blogs. So the forum has its own source of traffic.

The forum's niche interests and relatively advanced learning topics I think is what holds it back in terms of regular visitors. Instead of me trying to fight against it, better let it be what it wants to be, and let Kanji Koohii focus on what it wants to be.

I understand long time members still feel a connection between the two, as I do, so there is the link for members. It's a good compromise in my eyes.
> the forum seems like something to promote from the main page

I spent a ton of work on the forum upgrading it to MyBB and creating a completely new theme from scratch which is responsive and mobile friendly. The results? Nada. It's always been hovering around ~ 150 daily visitors.

It's healthy and it's carved its own little niche, but it's not growing in terms of active audience. The audience built itself originally around the "Reviewing the Kanji" user base, but nowadays it has incoming links from relatively advanced learning communities and blogs. So the forum has its own source of traffic.

The forum's niche interests and relatively advanced learning topics I think is what holds it back in terms of regular visitors. Instead of me trying to fight against it, better let it be what it wants to be, and let Kanji Koohii focus on what it wants to be.

I understand long time members still feel a connection between the two, as I do, so there is the link for members. It's a good compromise in my eyes.
