### ISSUE TITLE
Something doesn't feel right about the three main-buttons' arrangement

### ISSUE THREAD

**Issue by carcols** [fabd/kanji-koohii#55]
The first thing I see when I log-in are the three green buttons that say "study"/"review"/"progress chart".

I actually can't remember what they used to look like, but with the new version something doesn't feel right. I'm not a designer, but I sense some sort of incompleteness or lack of order in those buttons that didn't use to be before.

I'm really not sure what unsettles me, but some ideas are:
- What about centering the three buttons and their contents around the dark boxes that contain them?
- What about making all the buttons the same width (I think it's specially this that gives me a sense of disarray).
- What about making the whole dark boxes a big button, with the main text on the middle, and the description below or above in smaller letters?).

**Comment by fabd** [comment]
I agree it's not quite right. I call that page the "home screen" because the logo takes you there (and I call the signed out page the "landing page"). The home screen feels a bit empty on mobile.

Did a quick test in the Chrome dev tools and I agree this looks a bit nicer:

![home-screen-buttons-centered](https://cloud.githubusercontent.com/assets/169391/22349333/8936b1e4-e40f-11e6-9528-600f86d3e02e.png)

Would that solve this issue? Or do you feel it needs something else?

Connected issues:

* Improve flow for new users #36
* Improve the Home screen #7

**Comment by fabd** [comment]
While I'm there, what do you think of the "push button" style? It's not something I want to abuse, but I felt like this would feel a bit more interactive on mobile.

**Comment by carcols** [comment]
First, something super weird: I got you reply on my email, and the picture that I see there is different than the one I see here in github... the one I'm seeing right now doesn't have the centered buttons (whereas on my email it has).

Now, regarding the centered buttons... it still feels kind of weird, can you try to make all the green buttons the same width? Then I won't be sure if it would look better centered or to the left.

Regarding the "push button"... do you mean one of those red buttons they use in the movies to launch rockets? If so, I think these green buttons look better.

**Comment by fabd** [comment]
(Sorry I messed up the upload earlier)

DESKTOP

![issue 55 fix 1b](https://cloud.githubusercontent.com/assets/169391/22366632/0ef8bd90-e47e-11e6-94e1-9b89a3b11b58.png)

MOBILE

![issue55 fix1a](https://cloud.githubusercontent.com/assets/169391/22366633/11cfa452-e47e-11e6-951a-ee3344d0c7f4.png)


@carcols Would that solve the issue? (keeping in mind the Home screen otherwise needs a broader redesign)

Here I'm just looking for a quick fix that make it a bit nicer. Further redesign should go to Improve the Home screen #7

**Comment by fabd** [comment]
Sec, putting it up on **staging**

**Comment by carcols** [comment]
Yes it looks much better now.

On the desktop view it's perfect.

On the mobile view it's fine. The problem now, that would belong to another
discussion, is that it's kind of funny that only 3 buttons take the whole
screen.

Otherwise now it feels more organized.
Best,
Carlos

**Comment by carcols** [comment]
BTW, for thoroughness, maybe try not to center the buttons (i.e., put them
on the left) or make the green buttons take the whole vertical space. Then
maybe you can ask for some 3rd opinion, since I acknowledge I may have some
biases of website design.

**Comment by fabd** [comment]
Yes it feels weird because it's not very meaningful.

I'll consider this closed for now. (updating live soon)

In #7 some things I can try is put an overall progress bar on the Home Screen. But this requires also rethinking the concept of goals. Currently RTK and RTK 3 are kind of hardcoded in the site as one progress. If I make them two separate goals, and the user picks a goal, then it's easier to present that info on the homescreen. In other words right now the user doesn't explicitly get to say "I want to complete RTK3"
