### ISSUE TITLE
Let users create stories for multi-character words

### ISSUE THREAD

**Issue by dieps** [fabd/kanji-koohii#63]
I love your work, and I would love to see a possibility for users expanding the current vocabulary list to include compound words such as "movie" 映画 or "today" 今日.

**Comment by fabd** [comment]
Hi dieps. Hmm I'm not quite sure what you mean here. You are talking about the "Dictionary" section of the Study page right? Are you suggesting a change to the displayed entries?

**Comment by dieps** [comment]
Right now, the available kanji are single character words, but for words made by combining words.. such as telephone (電話) which combines electricity (電) and speak (話), users cannot submit stories for these word. I hope I was able to communicate the idea clearly.

**Comment by fabd** [comment]
Ah I see. That is outside of the scope of the website atm.

Imho, I don't think there is a big use case for sharing mnemonics for kanji compounds. There are many words where it seems atractive, such as 今日. But you'll find countless words made of 2 or 3 kanji that have relatively abstract keyword or unrelated keywords. Mnemonics could make sense for a difficult word that you need in daily use I suppose. 今日 is not a great example because it kind of reads as a mnemonic right? "now day" So it already is a mnemonic when read via RTK keywords.

The closest to it I can think of is that I want to add vocabulary to flashcards some day (which requires first: Refactor the Flashcard Review page as a VueJS component #38 ). Then I have a list of vocab per user, so I can add a vocab review mode. And then you make me realize it would be useful to also add a custom text area to these cards making them much more interesting. And, you just made me realize I could also add a "Share" option like the stories.. so it would be possible to see notes from other people relating to the same vocab. It start sounding similar to your suggestion.. but not quite the same as people can add anything they want (example sentence, mnemonic, or eg. a definition in Japanese).

I can not implement anything like that soon as I need to focus, but I will remember this when I can finally add words to the flashcards (ie. user added words rather than the random example words the site currently provides).

**Comment by fabd** [comment]
On further thought, it may be better to leave these topics open for some time in case other people want to comment.
