### ISSUE TITLE
Non-aligned blog column with buttons on home screen

### ISSUE THREAD

**Issue by carcols** [fabd/kanji-koohii#74]
When I access the website on the desktop now I see that the blog column and the buttons are all padded to the left, whereas before they were centered and looked much better. The effect is that the third green button (progress chart) looks completely out of place.

![image](https://cloud.githubusercontent.com/assets/11387647/22863039/f9dc21cc-f139-11e6-9f11-d2fdf04baffb.png)

**Comment by fabd** [comment]
Dammit I didn't get away with it :blush:  :sweat: 

I know.. I thought the blog posts were too stretched horizontally making for too long lines of text. It doesn't  look great, I'll admit.

I just don't know how to use the space. Thought about centering the blog , but that makes the top feel like it's hanging on either ends.

I'd say it's relatively minor but I'll keep the issue open as it is definitely not an acceptable solution so far.

The solution may come as part of : Improve the Home screen #7 

I think the problem here is the blog is just used to fill the space. It would better be on a separate page, and use some kind of notification system like many apps / sites do so user can be notified when there is a new post. And then basically use the entire screen as a useful home page (a simple design I came across recently could look [like this](https://cdn-images-1.medium.com/max/1000/1*iVxqtPP23OSI3AeNA5cVcQ.gif) .. I mean, that's one way of filling the space). 

A simpel design I

**Comment by fabd** [comment]
Another temporary fix perhaps would be a slightly less wide column, centered, similar to the Donate page, as long as I can fit the top content inside it.
